services:
  - type: web
    name: taggingapi-api 
    runtime: docker
    rootDir: api
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tagging-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://taggingapi.onrender.com # Define as origens permitidas para consumo da API
      - key: API_KEY
        sync: false
      - key: ADMIN_KEY # Chave utilizada para operar métodos persistentes no banco de dados 
        sync: false
      - key: DEDUP_TTL
        value: "2.0" # Intervalo em segundos para avaliar duplicação

  - type: web
    name: taggingapi
    runtime: static
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
    envVars:
      - key: API_URL
        value: https://taggingapi-api.onrender.com

databases:
  - name: tagging-db
    plan: free